name = "flyology_tui"
description = "A typed, declarative terminal user-interface toolkit for Ada"
version = "0.1.1-dev"

authors = ["Yurii Rashkovskii"]
maintainers = ["Yurii Rashkovskii <yrashk@gmail.com>"]
maintainers-logins = ["yrashk"]
licenses = "MIT OR Apache-2.0"
website = "https://tui.flyology.org/"
tags = ["ada", "tui", "terminal", "ui", "elm"]
project-files = ["flyology_tui.gpr"]

[[depends-on]]
gnat = ">=13 & <17"

[available.'case(os)']
'linux|macos' = true
'...' = false

[[actions]]
type = "test"
command = ["./scripts/test.sh"]
