const commonOwnership = [
  "The application owns the model and applies updates in its serial event loop.",
  "Appearance and skin values are borrowed only while the component renders."
];

const component = (value) => ({
  ownership: commonOwnership,
  ...value
});

export const components = [
  component({
    slug: "accordions", title: "Accordions", group: "Navigation",
    summary: "Expand bounded sections while callers retain each section body.",
    use: "Use an accordion when several related sections share one narrow region and users usually need one section at a time.",
    model: "The model stores stable section IDs, expansion state, focus, and capture. Body surfaces remain caller-owned.",
    interaction: "Arrow keys move between headers. Enter, Space, and matching mouse release toggle the focused section.",
    kind: "accordion",
  }),
  component({
    slug: "breadcrumbs", title: "Breadcrumbs", group: "Navigation",
    summary: "Show a bounded path with stable IDs and responsive truncation.",
    use: "Use breadcrumbs to show hierarchy and let users return to an ancestor without opening a separate menu.",
    model: "Active and focused items survive reorder by stable ID. Width changes recompute visible items and ellipses.",
    interaction: "Left and Right move focus. Enter, Space, or mouse activation returns the selected ancestor ID.",
    kind: "breadcrumbs",
  }),
  component({
    slug: "buttons", title: "Buttons", group: "Controls",
    summary: "Activate a labeled command after a complete press and release gesture.",
    use: "Use a button for an immediate, named action. Keep persistent choices in check boxes, radios, or selectors.",
    model: "The label and appearance stay outside the interaction model. The model retains focus, hover, armed state, and capture.",
    interaction: "Enter and Space activate immediately. A mouse press arms the button; only a matching release inside activates it.",
    kind: "button",
  }),
  component({
    slug: "chats", title: "Chats", group: "Content",
    summary: "Render only the visible subset of heterogeneous messages, actions, a footer, and a composer.",
    use: "Use Chats for ordinary conversations or AI transcripts whose message bodies can be any caller-owned component surface.",
    model: "The chat owns stable message metadata, measurements, viewport state, selection, automatic tail-following state, and unread counts. Bodies remain external.",
    interaction: "Route input to visible child body and action regions before transcript scrolling. The application owns input-area submission.",
    kind: "chat",
  }),
  component({
    slug: "check-boxes", sourceSlug: "check_boxes", title: "Check boxes", group: "Controls",
    summary: "Represent unchecked, checked, and mixed boolean state.",
    use: "Use a check box for an independent option. Use a radio group when exactly one choice must remain active.",
    model: "The model retains tri-state value and interaction state. Programmatic setters cancel stale activation without losing pending release ownership.",
    interaction: "Space toggles the focused value. A mouse gesture toggles only after a matching release.",
    kind: "checkbox",
  }),
  component({
    slug: "dock-workspaces", sourceSlug: "dock_workspaces", title: "Dock workspaces", group: "Layout",
    summary: "Dock, collapse, float, move, and restore caller-owned panes.",
    use: "Use a dock workspace when users must reorganize major tool panes while the application retains global ownership.",
    model: "At most one pane occupies each edge. Floating panes retain their return edge, and an immutable presentation aligns render and hit regions.",
    interaction: "Headers support mouse drag and keyboard docking. Collapsed rails remain focusable, and matching release always clears capture.",
    kind: "dock",
  }),
  component({
    slug: "dropdowns", title: "Dropdowns", group: "Controls",
    summary: "Choose one stable-ID item from a bounded popup list.",
    use: "Use a dropdown when one choice must fit in a compact closed control. Prefer radios when all choices you want all choices to remain visible.",
    model: "The model retains selected ID, highlight, open state, focus, and capture. Item labels are supplied by the generic instance.",
    interaction: "Enter or Space opens and commits. Escape and outside click dismiss. Arrow keys and wheel movement change the highlight.",
    kind: "dropdown",
  }),
  component({
    slug: "forms", title: "Forms", group: "Content",
    container: true,
    summary: "Lay out labels and caller-owned field surfaces in bounded rows.",
    use: "Use Forms to align related input fields and values. Field interaction and validation remain in each child model.",
    model: "The form retains responsive width and label-column geometry, not the child field models or their values.",
    interaction: "The application routes events to child regions returned by the form layout and owns focus traversal.",
    kind: "form",
  }),
  component({
    slug: "gradients", title: "Gradients", group: "Visualization",
    passive: true,
    ownership: ["The caller owns the target surface and the bounded gradient stops.", "The gradient borrows its region and color application mode for one call."],
    summary: "Apply bounded semantic color gradients to complete terminal cells.",
    use: "Use gradients to communicate progression, intensity, or grouping on high-color terminals while retaining a useful reduced-color result.",
    model: "A fixed-capacity stop model validates the complete stop order before changing state. Rendering preserves glyphs, attributes, and complete wide spans.",
    interaction: "Gradients are presentation-only. Color profiles progressively reduce truecolor output to ANSI 256, ANSI 16, or monochrome.",
    kind: "gradient",
  }),
  component({
    slug: "help", title: "Help", group: "Feedback",
    passive: true,
    ownership: ["Help retains no model state.", "The caller supplies bindings, width, orientation, and appearance for each render."],
    summary: "Render compact key and command hints horizontally or vertically.",
    use: "Use Help for persistent shortcuts near the surface they affect. Keep long explanations in guide text.",
    model: "Help is stateless. The caller supplies bounded bindings and explicit key and detail styles.",
    interaction: "Help renders labels only and never consumes input.",
    kind: "help",
  }),
  component({
    slug: "indicators", title: "Indicators", group: "Feedback",
    passive: true,
    ownership: ["Indicator functions retain no model state.", "The caller supplies values, width, and appearance for each render."],
    summary: "Render badges, dividers, gauges, key-value rows, and status lines.",
    use: "Use indicators for compact, read-only state that must remain legible beside interactive controls.",
    model: "Indicator renderers are stateless. Status-line capacity is explicit and rejected before partial output.",
    interaction: "Indicators do not take focus or consume events.",
    kind: "indicators",
  }),
  component({
    slug: "interactions", title: "Interaction results", group: "Foundation",
    foundation: true,
    ownership: ["An interaction result is a detached value.", "The application owns focus and mouse capture and applies the requested capture action."],
    summary: "Share handled, changed, activation, rejection, focus, and capture results.",
    use: "Use the common result vocabulary when an application coordinates several components without callbacks.",
    model: "A component update result is a detached value. Capture actions explicitly acquire or release application-owned mouse capture.",
    interaction: "Applications inspect the result after Update, mutate their own domain state, then schedule another render.",
    kind: "interaction",
  }),
  component({
    slug: "lists", title: "Lists", group: "Navigation",
    summary: "Navigate a bounded vertical list with responsive viewport geometry.",
    use: "Use Lists for simple homogeneous rows. Use Tables for columns and Trees for hierarchy.",
    model: "The model retains focus, selected row, top row, and configured dimensions. Content surfaces remain external.",
    interaction: "Arrows, Page Up, Page Down, Home, End, wheel, and row clicks clamp the visible selection at numeric limits.",
    kind: "list",
  }),
  component({
    slug: "markdown-editors", sourceSlug: "markdown_editors", title: "Markdown editors", group: "Editing",
    summary: "Compose a bounded source editor with live Markdown preview layouts.",
    use: "Use a Markdown editor when users need source, preview, or responsive split modes from one bounded document.",
    model: "A limited model owns one text area and one viewer in place. Text mutations synchronize the preview; cursor-only changes do not reset it.",
    interaction: "The application routes input to the source or preview region from the current immutable layout.",
    kind: "markdownEditor",
  }),
  component({
    slug: "markdown-viewers", sourceSlug: "markdown_viewers", title: "Markdown viewers", group: "Content",
    summary: "Parse and present a bounded read-only Markdown subset incrementally.",
    use: "Use a Markdown viewer for documentation, help, or message bodies that need links and structured text without web rendering.",
    model: "The viewer owns bounded source, line, link, parse, scroll, and selection state. Parsing and rendering advance under caller budgets.",
    interaction: "Keyboard and mouse activate typed link IDs. Stale presentation snapshots are rejected after source replacement.",
    kind: "markdown",
  }),
  component({
    slug: "menubars", title: "Menubars", group: "Navigation",
    summary: "Present typed top-level, popup, and nested application commands.",
    use: "Use a menubar for global commands that need mnemonics, shortcuts, check items, radio items, and bounded submenus.",
    model: "The model validates the complete menu graph before changing state and preserves mutable state by stable ID. Presentation revisions reject stale overlay input.",
    interaction: "Menus take modal routing priority while open. Keyboard mnemonics, arrows, Escape, mouse hover, and complete click gestures have parity.",
    kind: "menubar",
  }),
  component({
    slug: "panel-groups", sourceSlug: "panel_groups", title: "Panel groups", group: "Layout",
    summary: "Resize an arbitrary bounded sequence of panes at shared dividers.",
    use: "Use a panel group for jointly resizable horizontal or vertical work areas with more than two children.",
    model: "Initial sizes, weights, minima, pane bounds, focused divider, and capture stay in the model. Children remain caller-owned.",
    interaction: "Drag a shared divider with the mouse or move the focused divider with arrows. Tab changes the focused divider.",
    kind: "panels",
  }),
  component({
    slug: "progress", title: "Progress", group: "Feedback",
    passive: true,
    ownership: ["The application owns the progress model and sets its retained value and width.", "The component retains no timer, task, or input state."],
    summary: "Render a single determinate progress value at a responsive width.",
    use: "Use a progress bar for one bounded operation. Use progress groups when several jobs need selection, lifecycle, and aggregate state.",
    model: "The model retains current value, maximum, width, and label geometry. It never owns a timer or task.",
    interaction: "Progress is read-only. The application advances it through ordinary model updates.",
    kind: "progress",
  }),
  component({
    slug: "progress-groups", sourceSlug: "progress_groups", title: "Progress groups", group: "Feedback",
    summary: "Track typed jobs with determinate, indeterminate, and lifecycle states.",
    use: "Use progress groups for a bounded set of work items that need selection, aggregate progress, and distinct work states.",
    model: "Stable typed IDs survive reorder. Phase changes occur only when the application explicitly advances the model; no timer or task is retained.",
    interaction: "Keyboard, wheel, and local mouse input select rows. Rendering can show rows or a deterministic segmented aggregate.",
    kind: "progressGroup",
  }),
  component({
    slug: "radio-groups", sourceSlug: "radio_groups", title: "Radio groups", group: "Controls",
    summary: "Select exactly one stable-ID option from a visible bounded group.",
    use: "Use radio groups when comparing all choices matters and exactly one item must be active.",
    model: "The model retains selected and focused IDs plus capture. Disabled items remain present but are skipped by navigation.",
    interaction: "Arrows move and select. Enter, Space, and matching mouse release activate the focused option.",
    kind: "radio",
  }),
  component({
    slug: "scrollbars", title: "Scrollbars", group: "Navigation",
    summary: "Bind a viewport offset to arrow, track, wheel, and thumb input.",
    use: "Use Scrollbars beside a real scrollable region. The application owns the two-way synchronization with content offsets.",
    model: "The model retains orientation, range, page size, first item, focus, and capture. It does not own the scrolled content.",
    interaction: "Arrows move one unit, track clicks move one page, wheel moves by signed magnitude, and thumb drag uses captured motion.",
    kind: "scrollbar",
  }),
  component({
    slug: "selectors", title: "Selectors", group: "Controls",
    summary: "Select one or several stable-ID items from a visible list.",
    use: "Use a selector when choices you want all choices to remain visible and multi-selection may be required.",
    model: "Single and multiple modes share bounded item storage. The model validates the complete replacement before it changes the selection.",
    interaction: "Arrows move focus. Space and mouse release toggle according to the configured selection mode.",
    kind: "selector",
  }),
  component({
    slug: "sparklines", title: "Sparklines", group: "Visualization",
    passive: true,
    ownership: ["The caller owns the bounded numeric series.", "The renderer borrows the series, scale, width, and appearance for one call."],
    summary: "Render a bounded numeric suffix as a compact bar series.",
    use: "Use Sparklines when trend and shape matter more than exact axis labels.",
    model: "The caller supplies a fixed-capacity numeric series. Automatic or fixed scaling validates finite values before glyph selection.",
    interaction: "Sparklines are read-only and take no focus.",
    kind: "sparkline",
  }),
  component({
    slug: "spinners", title: "Spinners", group: "Feedback",
    passive: true,
    ownership: ["The caller owns the phase and advances it from an application event.", "The spinner retains no timer or task."],
    summary: "Show caller-advanced activity without owning time or work.",
    use: "Use a spinner for activity whose completion ratio is unknown. Prefer progress when a useful ratio exists.",
    model: "The model retains one bounded phase. The application advances the phase from its own tick event.",
    interaction: "Spinners do not take focus or schedule updates.",
    kind: "spinner",
  }),
  component({
    slug: "split-panes", sourceSlug: "split_panes", title: "Split panes", group: "Layout",
    summary: "Resize two caller-owned panes at one shared boundary.",
    use: "Use split panes for a two-region editor, navigator, or preview. Use a panel group for three or more panes.",
    model: "The model retains orientation, first span, minima, focus, and capture. Resize computes deterministic child and divider regions.",
    interaction: "Drag the divider or use arrows while focused. Matching release clears capture after resize or disable changes.",
    kind: "split",
  }),
  component({
    slug: "streaming-texts", sourceSlug: "streaming_texts", title: "Streaming texts", group: "Content",
    summary: "Append bounded output with automatic tail-following and unseen-chunk state.",
    use: "Use streaming text for logs, command output, or AI response text that arrives in chunks.",
    model: "Fixed code-point, line, and viewport-cell capacities bound retained output. Append can reject or trim complete old lines and clusters.",
    interaction: "Keyboard and wheel input scroll. The caller appends chunks and explicitly finishes, fails, or cancels the stream.",
    kind: "stream",
  }),
  component({
    slug: "syntax-editors", sourceSlug: "syntax_editors", title: "Syntax editors", group: "Editing",
    summary: "Compose bounded multiline editing with token highlighting with a caller-selected line limit.",
    use: "Use a syntax editor when source text needs responsive editing plus a deterministic external lexer.",
    model: "One text-area state machine owns editing. A bounded per-line token cache stores validated cluster-boundary spans and lexer state.",
    interaction: "Editing behavior matches a text area. The caller advances highlighting under an explicit line budget.",
    kind: "syntax",
  }),
  component({
    slug: "tables", title: "Tables", group: "Data",
    summary: "Render typed columns, stable rows, sorting, selection, and viewport state.",
    use: "Use Tables for homogeneous records whose columns need independent widths and sort behavior.",
    model: "Source order and display order stay separate. Stable row IDs preserve selection and focus through reorder and stable sorting.",
    interaction: "Header focus controls three-state sorting. Row focus controls selection and vertical navigation; wheel input changes the viewport.",
    kind: "table",
  }),
  component({
    slug: "tabs", title: "Tabs", group: "Navigation",
    summary: "Switch stable-ID pages with responsive clipping and persistent active state.",
    use: "Use Tabs for sibling views at one hierarchy level. Keep application-wide commands in a menubar.",
    model: "The model retains active and focused IDs. An immutable presentation maps visible tab regions after clipping.",
    interaction: "Arrows move focus, Enter and Space activate, and matching mouse release activates the pressed tab.",
    kind: "tabs",
  }),
  component({
    slug: "text-areas", sourceSlug: "text_areas", title: "Text areas", group: "Editing",
    summary: "Edit bounded multiline Unicode text with selection, history, and wrapping.",
    use: "Use a text area for multiline input, notes, source, or a composer. Use streaming text for non-editable append-only output.",
    model: "A limited model owns normalized LF text, cursor, selection, bounded undo history, viewport, and capture. If capacity is insufficient, the operation leaves state unchanged.",
    interaction: "Grapheme-aware keys, page movement, wheel scrolling, click-drag selection, paste, undo, and redo share one state machine.",
    kind: "textarea",
  }),
  component({
    slug: "text-inputs", sourceSlug: "text_inputs", title: "Text inputs", group: "Editing",
    summary: "Edit one bounded Unicode line with cursor and selection state.",
    use: "Use a text input for names, filters, paths, and short commands that must remain on one line.",
    model: "The model retains bounded value, cursor, selection, horizontal viewport, focus, and capture. Labels and appearance remain external.",
    interaction: "Keyboard editing, paste, pointer placement, and drag selection operate on grapheme boundaries.",
    kind: "textinput",
  }),
  component({
    slug: "trees", title: "Trees", group: "Data",
    summary: "Navigate a validated bounded preorder tree with stable expansion state.",
    use: "Use Trees for hierarchical data whose children can expand and collapse in place.",
    model: "The model validates the complete preorder depth sequence before it changes state. Expansion, selection, focus, and viewport survive replacement by stable ID.",
    interaction: "Left collapses or moves to the parent. Right expands or moves to the first child. Rows also support mouse and wheel input.",
    kind: "tree",
  }),
  component({
    slug: "viewports", title: "Viewports", group: "Layout",
    summary: "Clip a caller-owned surface and expose bounded horizontal and vertical offsets.",
    use: "Use Viewports when content can exceed its visible region. Pair them with Scrollbars when users need persistent position affordances.",
    model: "The viewport retains visible size and offsets, not the content surface. Offset setters clamp to current content bounds.",
    interaction: "Arrows, Page keys, and wheel input move offsets. The application synchronizes any attached scrollbar models.",
    kind: "viewport",
  }),
  component({
    slug: "windows", title: "Windows", group: "Layout",
    summary: "Move, resize, focus, close, and layer in-terminal surfaces.",
    use: "Use Windows for floating work surfaces inside a terminal workspace. The application still owns z-order and modal routing.",
    model: "The model retains bounds, minima, enabled state, focus, and capture. Titles, content, appearance, and child models stay external.",
    interaction: "Drag the header to move and any border or corner to resize. Alt+Arrow keys move the window; Ctrl+Arrow keys resize it; close returns a typed request.",
    kind: "window",
  })
];

export const groups = [
  "Controls", "Editing", "Navigation", "Data", "Layout",
  "Content", "Feedback", "Visualization", "Foundation"
];

export const skins = [
  { id: "charm-default", label: "Charm" },
  { id: "charm-dark", label: "Charm dark" },
  { id: "charm-light", label: "Charm light" },
  { id: "turbo-vision", label: "Turbo Vision" }
];
